config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :categories
  resources :tags
  root :to => redirect('/posts')

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts
      resources :tags
      resources :categories
      root :to => redirect('/api/v1/posts')
    end
  end

end

app/models/post.rb
  # create_table "posts", force: true do |t|
  #   t.string   "title"
  #   t.text     "body"
  #   t.datetime "created_at"
  #   t.datetime "updated_at"
  #   t.integer  "category_id"
  # end

require 'elasticsearch/model'

class Post < ActiveRecord::Base
  self.table_name = 'posts'
  self.primary_key = 'id'

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  has_many :posts_tags
  has_many :tags, through: :posts_tags, after_add: [ lambda { |a,c| a.__elasticsearch__.index_document } ], after_remove: [ lambda { |a,c| a.__elasticsearch__.index_document } ]

  belongs_to :category

  attr_accessor :title_highlighted, :body_highlighted, :category_highlighted, :tags_highlighted

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :title, analyzer: 'english', index_options: 'offsets'
      indexes :body, analyzer: 'english'
      indexes :tag_list, type: :string, analyzer: 'snowball'
      indexes :category_name
    end
  end

  def tag_list
    tags && tag_names
  end

  def tag_names
    tag_names = []
    tags.each do |tag|
      tag_names << tag.name
    end
    tag_names
  end

  def category_name
    category && category.name
  end

  INDEXABLE_METHODS = %i(title body category_name tag_list)

  def as_indexed_json(options={})
    {}.tap do |json|
      INDEXABLE_METHODS.each { |method| json[method] = send method }
    end
  end

  # This is equivalent to the above
  # def as_indexed_json(options={})
  #   {
  #     title: title,
  #     body: body,
  #     category_name: category_name,
  #     tag_list: tag_list
  #   }
  # end

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fuzziness: 1.5,
            fields: ['tag_list^10', 'category_name^8', 'title^5', 'body']
          }
        },
        highlight: {
          pre_tags: ['<em>'],
          post_tags: ['</em>'],
          fields: {
            title: {},
            body: {},
            category_name: {},
            tag_list: {}
          }
        }
      }
    )
  end

end

# Delete the previous posts index in Elasticsearch
Post.__elasticsearch__.client.indices.delete index: Post.index_name rescue nil

# Create the new index with the new mapping
Post.__elasticsearch__.client.indices.create \
  index: Post.index_name,
  body: { settings: Post.settings.to_hash, mappings: Post.mappings.to_hash }

# Index all Post records from the DB to Elasticsearch
Post.import # for auto sync model with elastic search

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      skip_before_filter :verify_authenticity_token
      respond_to :json

      def index
        # @posts = Post.all
        # @posts = Post.all.order("id DESC")
        @posts = Post.includes(:tags, :category).all.order("id DESC")
        @posts.each do |post|
          post.title_tags = post.title
          post.tags.each do |tag|
            post.title_tags += ' ' + tag.name
          end
        end
      end

      def show
        @post = Post.includes(posts_tags: :tag).find(params[:id])
      end

      def new
        # default: render 'new' template
        respond_with(Post.new)
      end

      def create
        @post = Post.new(post_params)
        if @post.save
          respond_to do |format|
            format.json {render :json => @post}
          end
        end
      end

      def update
        @post = Post.find(params[:id])
        respond_to do |format|
          if @post.update(post_params)
            format.json {render :json => @post}
          else
            format.json {render json: {errors: @post.errors}, status: :unprocessable_entity}
          end
        end
      end

      def destroy
        respond_with Post.destroy(params[:id])
      end

      private
        def post_params
          params.required(:post).permit(:title, :body, :category_id,
            posts_tags_attributes: [:id, :_destroy, :tag_id, tag_attributes: [:name]])
        end
    end
  end
end

#edit


# {
#     "id"=>"30",
#     "title"=>"a testttt",
#     "body"=>"testinnn",
#     "created_at"=>"2014-09-29T21:01:49.000Z",
#     "updated_at"=>"2014-09-29T21:01:49.000Z",
#     "category_id"=>4,
#     "tags"=>[
#         {
#             "name"=>"credit card"
#         },
#         {
#             "name"=>"Boom2"
#         },
#         {
#             "id"=>4,
#             "name"=>"field day",
#             "created_at"=>"2014-09-03T19:41:42.000Z",
#             "updated_at"=>"2014-09-03T20:09:58.000Z",
#             "route"=>"tags",
#             "reqParams"=>nil,
#             "fromServer"=>true,
#             "parentResource"=>nil,
#             "restangularCollection"=>false,
#             "tag_id"=>4
#         }
#     ],
#     "format"=>"json",
#     "action"=>"update",
#     "controller"=>"api/v1/posts",
#     "post"=>{
#         "id"=>30,
#         "title"=>"a testttt",
#         "body"=>"testinnn",
#         "created_at"=>"2014-09-29T21:01:49.000Z",
#         "updated_at"=>"2014-09-29T21:01:49.000Z",
#         "category_id"=>4
#     }
# }

# {
#   "title"=>"Why is there a charge to “Safety Courses 18008302268” on my credit card statement?",
#   "body"=>"This is the charge for your course fee. “Safety Courses 18008302268” is what appears on your card statement.",
#   "category_id"=>3
# }

#create

# {
#     "post"=>{
#         "posts_tags_attributes"=>[
#             {
#                 "id"=>9,
#                 "name"=>"Boom2",
#                 "created_at"=>"2014-09-24T23:00:42.000Z",
#                 "updated_at"=>"2014-09-24T23:00:42.000Z",
#                 "route"=>"tags",
#                 "reqParams"=>nil,
#                 "fromServer"=>true,
#                 "parentResource"=>nil,
#                 "restangularCollection"=>false,
#                 "tag_id"=>9
#             }
#         ],
#         "category_id"=>1,
#         "title"=>"test22",
#         "body"=>"test222"
#     },
#     "format"=>"json",
#     "action"=>"create",
#     "controller"=>"api/v1/posts"
# }

# {
#   "title"=>"test",
#   "body"=>"test",
#   "category_id"=>4,
#   "posts_tags_attributes"=>[{"tag_id"=>6}]
# }


# {
#   post: {
#     title: "dhwa",
#     tags_attributes: [
#       { id: 1, name: "Whatever" },
#       { id: 1, name: "Whatever" },
#     ]
#   }
# }

app/controllers/posts_controller.rb
require 'json'
require 'net/http'
require 'rubygems'
# require 'nokogiri'
require 'open-uri'

class PostsController < ApplicationController
  include PostsHelper
  skip_before_filter :verify_authenticity_token

  def index
    @response, @show_every_post = posts_from_parameters
    if @show_every_post == false
      @posts = @response.records.map_with_hit do |post, hit|
        highlight = hit.highlight
        if highlight
          # Rails.logger.info "highlight(title: #{highlight.title.inspect}, body: #{highlight.body.inspect})"
          post.title_highlighted = highlight.title[0] if highlight.title
          post.body_highlighted = highlight.body[0] if highlight.body
          post.category_highlighted = highlight.category_name[0] if highlight.category_name
          if highlight.tag_list
            post.tags_highlighted = []
            highlight.tag_list.each do |tag|
              post.tags_highlighted << tag
            end
          end
        end
        post
      end
    else
      @posts = @response
    end

    # Rails.logger.info "post titles " + ('~' * 100)
    # Rails.logger.info @posts.map { |p| p.title_highlighted.to_s }.join("\n")

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  def show
    @post = Post.includes(posts_tags: :tag).find(params[:id])

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  def new
    # default: render 'new' template
    @post = Post.new
  end

  def create
    # @post = Post.new(params[:post])
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.json { render action: "show", status: :created }
        format.xml { render xml: @post, status: :created }
      else
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.xml { render xml: @post.errors, status: :unprocessable_entity }
      end
    end

  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    # raise "hello"

    respond_to do |format|
      if @post.update_attributes(post_params)
        format.json { head :no_content, status: :ok }
        format.xml { head :no_content, status: :ok }
      else
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.xml { render xml: @post.errors, status: :unprocessable_entity }
      end
    end

  end

  def destroy
    @post = Post.find_by_id(params[:id])
    respond_to do |format|
      if @post.destroy
        format.json { head :no_content, status: :ok }
        format.xml { head :no_content, status: :ok }
      else
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.xml { render xml: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def fetch_from_url(url)
    response = Net::HTTP.get_response(URI.parse(url))
    data = response.body
    JSON.parse(data)
  end

    def post_params
      params.required(:post).permit(:id, :title, :body, :category_id, :tag_ids => [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper

  def posts_from_parameters
    posts = []
    show_every_post = true
    if params[:q].to_s.length == 0
      posts = Post.includes(:tags, :category).all.order("id DESC")
      show_every_post = true
      return posts, show_every_post
    else
      posts = Post.search params[:q]
      show_every_post = false
      return posts, show_every_post
    end
  end

end

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-sm-3">
  </div>
  <div class="col-sm-9">
    <div class="col-sm-9">
      <ol class="breadcrumb">
        <li>
          <%= link_to "Article", post_path(@post) %>
        </li>
        <li class="active">Edit</li>
      </ol>
    </div>

    <div class="col-sm-9">
      <%= simple_form_for @post, class: "form-horizontal" do |f| %>
        <legend>Edit Article</legend>
        <div class="form-group row">

          <div class='col-sm-1 control-label'>
            <%= f.label "Category" %>
          </div>

          <div class="col-sm-2">
            <%= f.select :category_id, Category.all.map { |r| [r.name, r.id] }, include_blank: true, class: 'form-control' %>
          </div>

          <div class="col-sm-3">
            <%= link_to new_category_path, class: "btn btn-info btn-small" do %>
              <i class="glyphicon glyphicon-plus"> Create New Category</i>
            <% end %>
          </div>

          <div class="col-sm-2">
          </div>
        </div>

        <div class="form-group row">

          <div class='col-sm-1 control-label'>
            <%= f.label "Title" %>
          </div>

          <div class="col-sm-8">
            <%= f.input_field :title, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">

          <div class='col-sm-1 control-label'>
            <%= f.label "Body" %>
          </div>

          <div class="col-sm-8">
            <%= f.input :body, :input_html => {:rows => 10, :cols => 100}, label: false, class: 'form-control'%>
          </div>
        </div>

        <div class="form-group row">

          <div class='col-sm-1 control-label'>
            <%= f.label "Tags" %>
          </div>

          <div class="col-sm-3">
              <%= f.association :tags, as: :check_boxes, label: false, class: 'form-control' %>
          </div>

          <div class="col-sm-3">
            <%= link_to new_tag_path, class: "btn btn-info btn-small" do %>
              <i class="glyphicon glyphicon-plus"> Create New Tag</i>
            <% end %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-offset-1 col-sm-8">
            <button type="submit" class="btn btn-primary">Save</button>
            <%= link_to post_path(@post), class: "btn btn-danger" do %>
              <i>Cancel</i>
            <% end %>
          </div>
        </div>

      <% end %>
    </div>

  </div>
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-sm-3">
    <div class="panel panel-default">
      <div class="panel-heading"><span class="glyphicon glyphicon-search"></span> Search</div>
      <div class="panel-body">
        <%= form_for posts_path, method: :get do |f| %>
          <div class="form-group">
            <%= text_field_tag :q, params[:q] %>
            <%= submit_tag "Go", name: nil %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-8">
    <div class="alert alert-info">
      <strong>Can't find what you're looking for?</strong>
      <%= link_to "Create an article.", new_post_path %>
    </div>

    <section class="search-results">
    <ul class="media-list">
      <% if @show_every_post == false %>
        <% @posts.each_with_hit do |post, hit| %>
          <li class="media">
            <div class="media-body">
              <h3 class="media-heading">
                <% if hit.try(:highlight).try(:title) && hit.try(:highlight).try(:category_name)%>
                  <%= link_to "[#{hit.highlight.category_name[0]}] #{hit.highlight.title[0]}".html_safe, post_path(post) %>
                <% elsif hit.try(:highlight).try(:title) && hit.try(:highlight).try(:category_name) == nil %>
                  <%= link_to "[#{post.category["name"]}] #{hit.highlight.title[0]}".html_safe, post_path(post) %>
                <% elsif hit.try(:highlight).try(:title) == nil && hit.try(:highlight).try(:category_name) %>
                  <%= link_to "[#{hit.highlight.category_name[0]}] #{post["title"]}".html_safe, post_path(post) %>
                <% else %>
                  <%= link_to "[#{post.category["name"]}] #{post["title"]}", post_path(post) %>
                <% end %>
              </h3>
              <% if hit.try(:highlight).try(:body) %>
                <% hit.highlight.body.each do |snippet| %>
                  <p align="justify"><strong><%= snippet.html_safe %></strong></p>
                <% end %>
              <% else %>
                <p align="justify"><strong><%= post["body"] %></strong></p>
              <% end %>
              <span><b>Updated on:</b> <%= post["updated_at"].in_time_zone("Central Time (US & Canada)").strftime("%m/%d/%Y at %I:%M%p") %></span>
              <i class="fa fa-tags"></i> <b>Tags:</b>
                <% if hit.try(:highlight).try(:tag_list) %>
                  <% hit.highlight.tag_list.each do |tag| %>
                    <span class="label label-info" style="color:green"><%= tag.html_safe %></span>
                  <% end %>
                <% end %>
                <% post.tags.each do |tag| %>
                  <% if hit.highlight.tag_list != nil %>
                    <% arr = [] %>
                    <% hit.highlight.tag_list.each do |highlightable_tag| %>
                      <% arr << highlightable_tag.gsub(/<[^>]*>/, "") %>
                    <% end %>
                    <% if !arr.include?("#{tag["name"]}") %>
                      <span class="label label-info"><%= tag["name"] %></span>
                    <% end %>
                  <% else %>
                    <span class="label label-info"><%= tag["name"] %></span>
                  <% end %>
                <% end %>
            </div>
          </li>
        <% end %>
      <% else %>
        <% @posts.each do |post| %>
          <li class="media">
            <div class="media-body">
              <h3 class="media-heading">
                <%= link_to "[#{post.category["name"]}] #{post["title"]}", post_path(post) %>
              </h3>
              <p align="justify"><strong><%= post["body"] %></strong></p>
              <span><b>Updated on:</b> <%= post["updated_at"].in_time_zone("Central Time (US & Canada)").strftime("%m/%d/%Y at %I:%M%p") %></span>
              <i class="fa fa-tags"></i> <b>Tags:</b> <% post.tags.each do |tag| %> <span class="label label-info"><%= tag["name"] %></span> <% end %>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-sm-3">
  </div>
  <div class="col-sm-9">
    <div class="col-sm-9">
      <ol class="breadcrumb">
        <li>
          <%= link_to "Articles", posts_path%>
        </li>
        <li class="active">Create</li>
      </ol>
    </div>

    <div class="col-sm-9">
      <%= simple_form_for @post, class: "form-horizontal" do |f| %>
        <legend>Create Article</legend>
        <div class="form-group row">

          <div class='col-sm-1 control-label'>
            <%= f.label "Category" %>
          </div>

          <div class="col-sm-2">
            <%= f.select :category_id, Category.all.map { |r| [r.name, r.id] }, include_blank: true, :input_html => {:size => 100}, class: 'form-control' %>
          </div>
          <div class="col-sm-3">
            <%= link_to new_category_path, class: "btn btn-info btn-small" do %>
              <i class="glyphicon glyphicon-plus"> Create New Category</i>
            <% end %>
          </div>
          <div class="col-sm-2">
          </div>
        </div>

        <div class="form-group row">

          <div class='col-sm-1 control-label'>
            <%= f.label "Title" %>
          </div>

          <div class="col-sm-8">
            <%= f.input_field :title, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">

          <div class='col-sm-1 control-label'>
            <%= f.label "Body" %>
          </div>

          <div class="col-sm-8">
            <%= f.input :body, :input_html => {:rows => 10, :cols => 100}, label: false, class: 'form-control'%>
          </div>
        </div>

        <div class="form-group row">

          <div class='col-sm-1 control-label'>
            <%= f.label "Tags" %>
          </div>

          <div class="col-sm-3">
              <%= f.association :tags, as: :check_boxes, label: false, class: 'form-control' %>
          </div>

          <div class="col-sm-3">
            <%= link_to new_tag_path, class: "btn btn-info btn-small" do %>
              <i class="glyphicon glyphicon-plus"> Create New Tag</i>
            <% end %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-offset-1 col-sm-8">
            <button type="submit" class="btn btn-primary">Publish</button>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-sm-3">
    <p><span class="glyphicon glyphicon-folder-open"></span> <strong> Category:</strong> <%= @post.category["name"] %></p>
    <p><span class="glyphicon glyphicon-tags"></span> <strong> Tags:</strong> </p>
    <ul class="list-inline">
      <% @post.tags.each do |tag| %>
      <li>
        <a><span class="label label-info"><%= tag["name"] %></span></a>
      </li>
      <% end %>
    </ul>
  </div>
  <div class="col-sm-7">
    <ol class="breadcrumb">
      <li>
        <%= link_to "Articles", posts_path%>
      </li>
      <li class="active">Article</li>
    </ol>
    <h2><%= @post["title"] %></h2>
    <p align="justify"><%= @post["body"] %> </p>

    <br>
    <div class="row">
      <div class="col-sm-12">
        <%= link_to edit_post_path(@post), class: "btn btn-primary btn-small" do %>
          <i class="glyphicon glyphicon-edit">Edit</i>
        <% end %>

        <%= link_to post_path(@post), class: "btn btn-danger btn-small", method: "delete", data: { confirm: "Are you sure?" } do %>
          <i class="glyphicon glyphicon-trash">Remove</i>
        <% end %>
      </div>
    </div>
  </div>
</div>